---
version: '2.1'
services:
  basedbin:
    image: cachyos-website-api:latest
    container_name: cachyos-website-api
    hostname: cachyoswebsiteapi
    environment:
      - DATABASE_URL=/db/website-api.db
      - RUNNING_ADDRESS=0.0.0.0
      - RUNNING_PORT=8088 # Defaults to 39764
    volumes:
      - ./db:/db:rw
    ports:
      - 8088:8088
    restart: always
